## Data Preproccesing

In [42]:
import pandas as pd
import numpy as np

In [43]:
business_df = pd.read_json('data/yelp_academic_dataset_business.json', lines=True)
business_df.head(10)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,1,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '..."
6,n_0UpQx1hsNbnPUSlodU8w,Famous Footwear,"8522 Eager Road, Dierbergs Brentwood Point",Brentwood,MO,63144,38.627695,-90.340465,2.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Sporting Goods, Fashion, Shoe Stores, Shopping...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-18:0', ..."
7,qkRM_2X51Yqxk3btlwAQIg,Temple Beth-El,400 Pasadena Ave S,St. Petersburg,FL,33707,27.766590,-82.732983,3.5,5,1,None,"Synagogues, Religious Organizations","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ..."
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,MO,63123,38.565165,-90.321087,3.0,19,0,"{'Caters': 'True', 'Alcohol': 'u'full_bar'', '...","Pubs, Restaurants, Italian, Bars, American (Tr...",None
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,10,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-21:0', '..."

In [44]:
user_df = pd.read_json('data/yelp_academic_dataset_user.json', lines=True,nrows=1_000_000)
user_df.head(10)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0
5,q_QQ5kBBwlCcbL1s4NVK3g,Jane,1221,2005-03-14 20:26:35,14953,9940,11211,"2006,2007,2008,2009,2010,2011,2012,2013,2014","xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg...",1357,...,163,191,361,147,1212,5696,2543,2543,815,323
6,cxuxXkcihfCbqt5Byrup8Q,Rob,12,2009-02-24 03:09:06,6,1,0,,"HDAQ74AEznP-YsMk1B14CA, 6A6-aIX7fg_zRy9MiE6YyQ...",1,...,0,0,0,0,0,1,0,0,0,0
7,E9kcWJdJUHuTKfQurPljwA,Mike,358,2008-12-11 22:11:56,399,102,143,,"y2GyxJF5VQWohxgw_GR7Jw, 0NRn4eY3JWN0IFqvOSa5gA...",23,...,7,2,0,0,8,6,12,12,5,0
8,lO1iq-f75hnPNZkTy3Zerg,Rachelle,40,2008-12-29 22:40:56,109,40,46,,"tOQDlz36rI__SOsbL-HCag, 83Xb0PPBwZiG2c_fLpZgAw...",7,...,0,0,3,0,3,4,5,5,3,1
9,AUi8MPWJ0mLkMfwbui27lg,John,109,2010-01-07 18:32:04,154,20,23,,"gy5fWeSv3Gamuq9Ox4MV4g, lMr3LWU6kPFLTmCpDkACxg...",4,...,0,0,0,0,1,6,3,3,0,0

In [45]:
checkin_df = pd.read_json('data/yelp_academic_dataset_checkin.json', lines=True)
checkin_df.head(10)

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020...
1  --0iUa4sNDFiZFrAdIWhZQ  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011...
2  --30_8IhuyMHbSOcNWd6DQ           2013-06-14 23:29:17, 2014-08-13 23:20:22
3  --7PUidqRWpRSpXebiyxTg  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012...
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014...
5  --8IbOsAAxjKRoYsBFL-PA  2015-06-06 01:03:19, 2015-07-29 16:50:58, 2015...
6  --9osgUCSDUWUkoTLdvYhQ  2015-06-13 02:00:57, 2015-07-04 00:44:09, 2015...
7  --ARBQr1WMsTWiwOKOj-FQ  2014-12-12 00:44:23, 2015-01-09 00:19:52, 2015...
8  --FWWsIwxRwuw9vIMImcQg  2010-09-11 16:28:39, 2010-12-22 21:14:19, 2011...
9  --FcbSxK1AoEtEAxOgBaCw  2017-08-18 19:43:50, 2017-10-07 22:38:38, 2017...

In [46]:
review_df = pd.read_json('data/yelp_academic_dataset_review.json', lines=True,nrows=2_000_000)
review_df.head(10)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1,1,2,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31
6,6AxgBCNX_PNTOxmbRSwcKQ,r3zeYsv1XFBRA4dJpL78cw,gmjsEdUsKpj9Xxu6pdjH0g,5,0,2,0,Loved this tour! I grabbed a groupon and the p...,2015-01-03 23:21:18
7,_ZeMknuYdlQcUqng_Im3yg,yfFzsLmaWF2d4Sr0UNbBgg,LHSTtnW3YHCeUkRDGyJOyw,5,2,0,0,Amazingly amazing wings and homemade bleu chee...,2015-08-07 02:29:16
8,ZKvDG2sBvHVdF5oBNUOpAQ,wSTuiTk-sKNdcFyprzZAjg,B5XSoSG3SfvQGtKEGQ1tSQ,3,1,1,0,This easter instead of going to Lopez Lake we ...,2016-03-30 22:46:33
9,pUycOfUwM8vqX7KjRRhUEA,59MxRhNVhU9MYndMkz0wtw,gebiRewfieSdtt17PTW6Zg,3,0,0,0,Had a party of 6 here for hibachi. Our waitres...,2016-07-25 07:31:06

In [47]:
tip_df = pd.read_json('data/yelp_academic_dataset_tip.json', lines=True)
tip_df.head(10)

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0
5,trf3Qcz8qvCDKXiTgjUcEg,7Rm9Ba50bw23KTA8RedZYg,"Chili Cup + Single Cheeseburger with onion, pi...",2012-03-13 04:00:52,0
6,SMGAlRjyfuYu-c-22zIyOg,kH-0iXqkL7b8UXNpguBMKg,"Saturday, Dec 7th 2013, ride Patco's Silver Sl...",2013-12-03 23:42:15,0
7,YVBB9g23nuVJ0u44zK0pSA,jtri188kuhe_AuEOJ51U_A,This is probably the best place in the cool Sp...,2016-11-22 22:14:58,0
8,VL12EhEdT4OWqGq0nIqkzw,xODBZmX4EmlVvbqtKN7YKg,Tacos,2012-07-27 01:48:24,0
9,4ay-fdVks5WMerYL_htkGQ,pICJRcyqW1cF96Q3XhLSbw,Starbucks substitute in boring downtown Tampa....,2012-06-09 22:57:04,0

In [48]:
def flatten_dict(data, parent_key='', sep='_'):
    """
    Recursively flatten nested dictionaries.

    Example:
        {'BusinessParking': {'garage': True, 'street': False}}

    becomes:
        {
            'BusinessParking_garage': True,
            'BusinessParking_street': False
        }
    """

    flattened = {}

    if not isinstance(data, dict):
        return flattened

    for key, value in data.items():

        # Create the new column name
        new_key = f"{parent_key}{sep}{key}" if parent_key else str(key)

        # If the value is another dictionary, recursively flatten it
        if isinstance(value, dict):
            flattened.update(
                flatten_dict(value, new_key, sep)
            )

        # Otherwise store the value
        else:
            flattened[new_key] = value

    return flattened

Handle null values for Bussiness dataset

In [49]:
business_df.isnull().sum()

business_id         0
name                0
address             0
city                0
state               0
postal_code         0
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes      13744
categories        103
hours           23223
dtype: int64

In [50]:
attributes_flattened = business_df['attributes'].apply(
    lambda x: flatten_dict(x)
)

In [51]:
attributes_df = pd.DataFrame(
    attributes_flattened.tolist(),
    index=business_df.index
)

In [52]:
print(attributes_df.shape)
print(attributes_df.columns.tolist())

(150346, 39)
['ByAppointmentOnly', 'BusinessAcceptsCreditCards', 'BikeParking', 'RestaurantsPriceRange2', 'CoatCheck', 'RestaurantsTakeOut', 'RestaurantsDelivery', 'Caters', 'WiFi', 'BusinessParking', 'WheelchairAccessible', 'HappyHour', 'OutdoorSeating', 'HasTV', 'RestaurantsReservations', 'DogsAllowed', 'Alcohol', 'GoodForKids', 'RestaurantsAttire', 'Ambience', 'RestaurantsTableService', 'RestaurantsGoodForGroups', 'DriveThru', 'NoiseLevel', 'GoodForMeal', 'BusinessAcceptsBitcoin', 'Smoking', 'Music', 'GoodForDancing', 'AcceptsInsurance', 'BestNights', 'BYOB', 'Corkage', 'BYOBCorkage', 'HairSpecializesIn', 'Open24Hours', 'RestaurantsCounterService', 'AgesAllowed', 'DietaryRestrictions']

In [53]:
hours_flattened = business_df['hours'].apply(
    lambda x: flatten_dict(x)
)

hours_df = pd.DataFrame(
    hours_flattened.tolist(),
    index=business_df.index
)
hours_df = hours_df.rename(
    columns={
        column: f"hours_{column}"
        for column in hours_df.columns
    }
)

In [54]:
business_df = pd.concat(
    [
        business_df,
        attributes_df, 
        hours_df
    ],
    axis=1
)

In [55]:
business_df.head(10)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,RestaurantsCounterService,AgesAllowed,DietaryRestrictions,hours_Monday,hours_Tuesday,hours_Wednesday,hours_Thursday,hours_Friday,hours_Saturday,hours_Sunday
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,NaN,NaN,NaN,0:0-0:0,8:0-18:30,8:0-18:30,8:0-18:30,8:0-18:30,8:0-14:0,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,NaN,NaN,NaN,8:0-22:0,8:0-22:0,8:0-22:0,8:0-22:0,8:0-23:0,8:0-23:0,8:0-22:0
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,NaN,NaN,NaN,7:0-20:0,7:0-20:0,7:0-20:0,7:0-20:0,7:0-21:0,7:0-21:0,7:0-21:0
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,NaN,NaN,NaN,NaN,NaN,14:0-22:0,16:0-22:0,12:0-22:0,12:0-22:0,12:0-18:0
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,...,NaN,NaN,NaN,0:0-0:0,6:0-22:0,6:0-22:0,6:0-22:0,9:0-0:0,9:0-22:0,8:0-22:0
6,n_0UpQx1hsNbnPUSlodU8w,Famous Footwear,"8522 Eager Road, Dierbergs Brentwood Point",Brentwood,MO,63144,38.627695,-90.340465,2.5,13,...,NaN,NaN,NaN,0:0-0:0,10:0-18:0,10:0-18:0,10:0-18:0,10:0-18:0,10:0-18:0,12:0-18:0
7,qkRM_2X51Yqxk3btlwAQIg,Temple Beth-El,400 Pasadena Ave S,St. Petersburg,FL,33707,27.766590,-82.732983,3.5,5,...,NaN,NaN,NaN,9:0-17:0,9:0-17:0,9:0-17:0,9:0-17:0,9:0-17:0,NaN,NaN
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,MO,63123,38.565165,-90.321087,3.0,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,10,...,NaN,NaN,NaN,0:0-0:0,6:0-21:0,6:0-21:0,6:0-16:0,6:0-16:0,6:0-17:0,6:0-21:0

In [56]:
business_df['categories'] = business_df['categories'].apply(
    lambda x: [category.strip() for category in x.split(',')]
    if pd.notna(x) else []
)

In [57]:
business_df = business_df.fillna('Unknown')

Handle null values for checkin dataset

In [58]:
checkin_df.isnull().sum()

business_id    0
date           0
dtype: int64

Handle null values for user_df

In [59]:
user_df.isnull().sum()

user_id               0
name                  0
review_count          0
yelping_since         0
useful                0
funny                 0
cool                  0
elite                 0
friends               0
fans                  0
average_stars         0
compliment_hot        0
compliment_more       0
compliment_profile    0
compliment_cute       0
compliment_list       0
compliment_note       0
compliment_plain      0
compliment_cool       0
compliment_funny      0
compliment_writer     0
compliment_photos     0
dtype: int64

In [60]:

def process_elite(value):
    if pd.isna(value) or value == '' or value == 'None':
        return pd.Series({
            'elite_years_count': 0,
            'elite_first_year': 'Unknown',
            'elite_last_year': 'Unknown',
            'is_elite': False
        })

    years = [
        int(year.strip())
        for year in str(value).split(',')
        if year.strip().isdigit()
    ]

    if not years:
        return pd.Series({
            'elite_years_count': 0,
            'elite_first_year': 'Unknown',
            'elite_last_year': 'Unknown',
            'is_elite': False
        })

    return pd.Series({
        'elite_years_count': len(years),
        'elite_first_year': min(years),
        'elite_last_year': max(years),
        'is_elite': True
    })


elite_df = user_df['elite'].apply(process_elite)

user_df = pd.concat(
    [
        user_df.drop(columns=['elite']),
        elite_df
    ],
    axis=1
)

In [61]:
user_df.columns

Index(['user_id', 'name', 'review_count', 'yelping_since', 'useful', 'funny',
       'cool', 'friends', 'fans', 'average_stars', 'compliment_hot',
       'compliment_more', 'compliment_profile', 'compliment_cute',
       'compliment_list', 'compliment_note', 'compliment_plain',
       'compliment_cool', 'compliment_funny', 'compliment_writer',
       'compliment_photos', 'elite_years_count', 'elite_first_year',
       'elite_last_year', 'is_elite'],
      dtype='object')

Handle miss values for tip_df dataset

In [62]:
tip_df.isnull().sum()

user_id             0
business_id         0
text                0
date                0
compliment_count    0
dtype: int64

Handle missing value for review_df dataset

In [63]:
review_df.isnull().sum()

review_id      0
user_id        0
business_id    0
stars          0
useful         0
funny          0
cool           0
text           0
date           0
dtype: int64

In [64]:
missing_review_users = review_df[
    ~review_df['user_id'].isin(user_df['user_id'])
]

# Businesses referenced in reviews that don't exist in business_df
missing_review_businesses = review_df[
    ~review_df['business_id'].isin(business_df['business_id'])
]

print("Missing users in reviews:", len(missing_review_users))
print("Missing businesses in reviews:", len(missing_review_businesses))

Missing users in reviews: 6
Missing businesses in reviews: 0

In [65]:
missing_tip_users = tip_df[
    ~tip_df['user_id'].isin(user_df['user_id'])
]

missing_tip_businesses = tip_df[
    ~tip_df['business_id'].isin(business_df['business_id'])
]

print("Missing users in tips:", len(missing_tip_users))
print("Missing businesses in tips:", len(missing_tip_businesses))

Missing users in tips: 154080
Missing businesses in tips: 0

In [66]:
missing_checkin_businesses = checkin_df[
    ~checkin_df['business_id'].isin(business_df['business_id'])
]

print("Missing businesses in checkins:", len(missing_checkin_businesses))

Missing businesses in checkins: 0

In [67]:
print("Reviews before:", len(review_df))
print("Tips before:", len(tip_df))

Reviews before: 2000000
Tips before: 908915

In [68]:
# Keep only reviews whose user_id exists in user_df
review_df = review_df[
    review_df['user_id'].isin(user_df['user_id'])
].copy()

# Keep only tips whose user_id exists in user_df
tip_df = tip_df[
    tip_df['user_id'].isin(user_df['user_id'])
].copy()

In [69]:
print("Missing users in reviews:",
      (~review_df['user_id'].isin(user_df['user_id'])).sum())

print("Missing users in tips:",
      (~tip_df['user_id'].isin(user_df['user_id'])).sum())

Missing users in reviews: 0
Missing users in tips: 0

In [70]:
print("Reviews after:", len(review_df))
print("Tips after:", len(tip_df))

Reviews after: 1999994
Tips after: 754835

In [71]:
checkin_df['date'] = checkin_df['date'].apply(
    lambda x: [date.strip() for date in x.split(',')]
    if isinstance(x, str) else []
)

In [72]:
checkin_df.head(10)

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  [2020-03-13 21:10:56, 2020-06-02 22:18:06, 202...
1  --0iUa4sNDFiZFrAdIWhZQ  [2010-09-13 21:43:09, 2011-05-04 23:08:15, 201...
2  --30_8IhuyMHbSOcNWd6DQ         [2013-06-14 23:29:17, 2014-08-13 23:20:22]
3  --7PUidqRWpRSpXebiyxTg  [2011-02-15 17:12:00, 2011-07-28 02:46:10, 201...
4  --7jw19RH9JKXgFohspgQw  [2014-04-21 20:42:11, 2014-04-28 21:04:46, 201...
5  --8IbOsAAxjKRoYsBFL-PA  [2015-06-06 01:03:19, 2015-07-29 16:50:58, 201...
6  --9osgUCSDUWUkoTLdvYhQ  [2015-06-13 02:00:57, 2015-07-04 00:44:09, 201...
7  --ARBQr1WMsTWiwOKOj-FQ  [2014-12-12 00:44:23, 2015-01-09 00:19:52, 201...
8  --FWWsIwxRwuw9vIMImcQg  [2010-09-11 16:28:39, 2010-12-22 21:14:19, 201...
9  --FcbSxK1AoEtEAxOgBaCw  [2017-08-18 19:43:50, 2017-10-07 22:38:38, 201...

Check duplicates

In [73]:
print("Duplicate users:", user_df['user_id'].duplicated().sum())

Duplicate users: 0

In [74]:
print("Duplicate businesses:", business_df['business_id'].duplicated().sum())

Duplicate businesses: 0

In [75]:
print("Duplicate reviews:", review_df.duplicated().sum())

Duplicate reviews: 0

In [76]:
print("Duplicate tips:", tip_df.duplicated().sum())

Duplicate tips: 59

In [78]:
duplicate_tips = tip_df[tip_df.duplicated(keep=False)]

print(duplicate_tips)

                       user_id             business_id  \
1644    SNZJNz1WEIMECEk-TAYADQ  6Gx45ltNNZvjzVBO6ZgVOg
11367   00Cz_vdInMHpTRjqbWjK5Q  ncacMQ9n_dSM1cR3c1vTQw
21583   Tf63LdfubjlFm974OrdTXg  CyiN_owscPJNvlwul0XJPg
29901   00Cz_vdInMHpTRjqbWjK5Q  ncacMQ9n_dSM1cR3c1vTQw
32192   y_PMpgAxTWUIYAmzfFc6VA  Bw0cpnfI-Y9QmjWzqS-oFg
...                        ...                     ...
714608  KDR-RHW_h4gap0A7jU2wHQ  WltG6PWu0zRTTUpWne3W8w
717186  VkisxivXasFfZ1ygMmyebQ  q0-vbZBHYEF48DMBzZ88sQ
718317  KDR-RHW_h4gap0A7jU2wHQ  WltG6PWu0zRTTUpWne3W8w
732384  6HcD_ikXQURCMbf5nZAZVg  0Nqa0zPHoB_GVucVMd9f6w
750446  6HcD_ikXQURCMbf5nZAZVg  0Nqa0zPHoB_GVucVMd9f6w

                                                     text                date  \
1644                               Great food, fun place! 2017-10-10 20:13:08
11367                                         Miss saigon 2010-12-07 01:59:12
21583                                                  LM 2011-11-22 12:48:02
29901                                         Miss saigon 2010-12-07 01:59:12
32192                      Late dinner w @steinerrecliner 2011-01-31 01:07:40
...                                                   ...                 ...
714608  This restaurant has been here since I've been ... 2014-04-02 02:41:58
717186                     In search of the Ghost Pepper. 2011-01-24 20:58:31
718317  This restaurant has been here since I've been ... 2014-04-02 02:41:58
732384                          This place is really nice 2017-09-05 03:36:35
750446                          This place is really nice 2017-09-05 03:36:35

        compliment_count
1644                   0
11367                  0
21583                  0
29901                  0
32192                  0
...                  ...
714608                 0
717186                 0
718317                 0
732384                 0
750446                 0

[110 rows x 5 columns]

In [79]:
tip_df = tip_df.drop_duplicates().copy()

In [80]:
print("Duplicate tips:", tip_df.duplicated().sum())

Duplicate tips: 0

In [81]:
import os

os.makedirs("data/processed", exist_ok=True)

user_df.to_csv("data/processed/users.csv", index=False)
business_df.to_csv("data/processed/businesses.csv", index=False)
review_df.to_csv("data/processed/reviews.csv", index=False)
tip_df.to_csv("data/processed/tips.csv", index=False)
checkin_df.to_csv("data/processed/checkins.csv", index=False)